import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { exportsDir } from "../core/paths.js";
import { componentList, componentReadSource } from "../core/components.js";
import { routeList } from "../core/routes.js";
import { loadTokens, resolveAll } from "../core/tokens.js";
import { E } from "../core/errors.js";
import type { ExportResult, ExportTarget } from "../types.js";

export type ExportFn = (projectDir: string, outDir: string) => string[];

export const EXPORTERS: Record<ExportTarget, ExportFn> = {
  "css-vars": exportCssVars,
  tailwind: exportTailwind,
  "style-dictionary": exportStyleDictionary,
  "react-shadcn": exportReactShadcn,
  "storybook-mdx": exportStorybookMdx,
  "route-map-md": exportRouteMapMd,
  "static-bundle": exportStaticBundle,
};

export function runExport(projectDir: string, target: ExportTarget, outDirAbs?: string): ExportResult {
  const exporter = EXPORTERS[target];
  if (!exporter) throw E.invalid("export target", `unknown target '${target}'`);
  const outDir = outDirAbs ?? join(exportsDir(projectDir), target);
  mkdirSync(outDir, { recursive: true });
  const files = exporter(projectDir, outDir);
  return { target, outDir, files };
}

function exportCssVars(projectDir: string, outDir: string): string[] {
  const tokens = resolveAll(loadTokens(projectDir).flat);
  const lines: string[] = [":root {"];
  for (const [k, v] of [...tokens].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  --${k.replace(/\./g, "-")}: ${v};`);
  }
  lines.push("}");
  const file = join(outDir, "tokens.css");
  writeFileSync(file, lines.join("\n") + "\n");
  return [file];
}

function exportTailwind(projectDir: string, outDir: string): string[] {
  const tokens = resolveAll(loadTokens(projectDir).flat);
  const config: Record<string, unknown> = {
    theme: { extend: { colors: {}, spacing: {}, fontSize: {}, borderRadius: {} } },
  };
  const theme = config.theme as { extend: Record<string, Record<string, string>> };
  for (const [k, v] of tokens) {
    if (k.startsWith("color.") || k.startsWith("accent.") || k.startsWith("surface.") || k.startsWith("text.") || k.startsWith("border.")) {
      theme.extend.colors![dotToCamel(k)] = v;
    } else if (k.startsWith("spacing.")) {
      theme.extend.spacing![k.slice("spacing.".length)] = v;
    } else if (k.startsWith("typography.size.")) {
      theme.extend.fontSize![k.slice("typography.size.".length)] = v;
    } else if (k.startsWith("radius.")) {
      theme.extend.borderRadius![k.slice("radius.".length)] = v;
    }
  }
  const file = join(outDir, "tailwind.config.cjs");
  writeFileSync(
    file,
    `/** Generated by loom. */\nmodule.exports = ${JSON.stringify(config, null, 2)};\n`,
  );
  return [file];
}

function exportStyleDictionary(projectDir: string, outDir: string): string[] {
  const { trees } = loadTokens(projectDir);
  const out: Record<string, unknown> = {};
  for (const [ns, tree] of Object.entries(trees)) {
    out[ns] = transformToSdShape(tree);
  }
  const file = join(outDir, "tokens.json");
  writeFileSync(file, JSON.stringify(out, null, 2));
  return [file];
}

function transformToSdShape(tree: unknown): unknown {
  if (tree === null || typeof tree !== "object") {
    return { value: tree };
  }
  const obj = tree as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v !== null && typeof v === "object") {
      out[k] = transformToSdShape(v);
    } else {
      out[k] = { value: v };
    }
  }
  return out;
}

function exportReactShadcn(projectDir: string, outDir: string): string[] {
  const files: string[] = [];
  files.push(...exportCssVars(projectDir, outDir));
  files.push(...exportTailwind(projectDir, outDir));

  // package.json
  const pkg = {
    name: `${baseName(projectDir)}-export`,
    private: true,
    type: "module",
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^18.3.0",
      "react-dom": "^18.3.0",
    },
    devDependencies: {
      vite: "^5.4.0",
      "@vitejs/plugin-react": "^4.3.0",
      typescript: "^5.7.0",
      tailwindcss: "^3.4.0",
      autoprefixer: "^10.4.0",
      postcss: "^8.4.0",
    },
  };
  const pkgFile = join(outDir, "package.json");
  writeFileSync(pkgFile, JSON.stringify(pkg, null, 2));
  files.push(pkgFile);

  // tsconfig + vite + postcss
  writeFileSync(
    join(outDir, "tsconfig.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["ES2022", "DOM"],
          jsx: "react-jsx",
          module: "ESNext",
          moduleResolution: "Bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          allowImportingTsExtensions: true,
          noEmit: true,
        },
        include: ["src", "components", "routes"],
      },
      null,
      2,
    ),
  );
  files.push(join(outDir, "tsconfig.json"));

  writeFileSync(
    join(outDir, "vite.config.ts"),
    `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({ plugins: [react()] });
`,
  );
  files.push(join(outDir, "vite.config.ts"));

  writeFileSync(
    join(outDir, "postcss.config.cjs"),
    `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };\n`,
  );
  files.push(join(outDir, "postcss.config.cjs"));

  // Copy components + routes
  mkdirSync(join(outDir, "components"), { recursive: true });
  mkdirSync(join(outDir, "routes"), { recursive: true });
  for (const c of componentList(projectDir)) {
    const sub = join(outDir, "components", c.name);
    mkdirSync(sub, { recursive: true });
    const src = componentReadSource(projectDir, c.name);
    writeFileSync(join(sub, `${c.name}.tsx`), src);
    files.push(join(sub, `${c.name}.tsx`));
  }
  for (const r of routeList(projectDir)) {
    const dest = join(outDir, "routes", `${routeToFileName(r.path)}.tsx`);
    mkdirSync(join(outDir, "routes"), { recursive: true });
    writeFileSync(dest, readFileSync(r.file, "utf8"));
    files.push(dest);
  }

  // src/main.tsx + index.html
  mkdirSync(join(outDir, "src"), { recursive: true });
  writeFileSync(
    join(outDir, "src", "main.tsx"),
    `import React from "react";
import ReactDOM from "react-dom/client";
import Home from "../routes/index";
import "../tokens.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode><Home /></React.StrictMode>,
);
`,
  );
  files.push(join(outDir, "src", "main.tsx"));
  writeFileSync(
    join(outDir, "index.html"),
    `<!doctype html><html><head><meta charset="utf-8"><title>${baseName(projectDir)}</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n`,
  );
  files.push(join(outDir, "index.html"));

  // README
  const readme = join(outDir, "README.md");
  writeFileSync(
    readme,
    `# ${baseName(projectDir)} — React + shadcn export\n\nGenerated by loom.\n\n## Run\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
  );
  files.push(readme);

  return files;
}

function exportStorybookMdx(projectDir: string, outDir: string): string[] {
  const files: string[] = [];
  mkdirSync(outDir, { recursive: true });
  for (const c of componentList(projectDir)) {
    const file = join(outDir, `${c.name}.stories.mdx`);
    const src = readFileSync(join(c.path, `${c.name}.stories.mdx`), "utf8");
    writeFileSync(file, src);
    files.push(file);
  }
  return files;
}

function exportRouteMapMd(projectDir: string, outDir: string): string[] {
  const routes = routeList(projectDir);
  const lines = ["# Route map", ""];
  for (const r of routes) {
    lines.push(`- \`${r.path}\` — ${r.meta.title ?? "(untitled)"} (${r.meta.state ?? "draft"})`);
  }
  const file = join(outDir, "routes.md");
  writeFileSync(file, lines.join("\n") + "\n");
  return [file];
}

function exportStaticBundle(projectDir: string, outDir: string): string[] {
  const tokens = resolveAll(loadTokens(projectDir).flat);
  const css = [":root {"];
  for (const [k, v] of [...tokens].sort(([a], [b]) => a.localeCompare(b))) {
    css.push(`  --${k.replace(/\./g, "-")}: ${v};`);
  }
  css.push("}");
  const routes = routeList(projectDir);
  const rendered = routes
    .map(
      (r) =>
        `<section data-route="${r.path}"><h2>${r.meta.title ?? r.path}</h2><pre>${escape(
          readFileSync(r.file, "utf8"),
        )}</pre></section>`,
    )
    .join("\n");
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${baseName(
    projectDir,
  )}</title><style>${css.join("\n")}</style></head><body>${rendered}</body></html>\n`;
  const file = join(outDir, "bundle.html");
  writeFileSync(file, html);
  return [file];
}

function dotToCamel(key: string): string {
  return key.replace(/\.(.)/g, (_, c) => c.toUpperCase());
}

function escape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function routeToFileName(path: string): string {
  if (path === "/") return "index";
  return path.replace(/^\//, "").replace(/\//g, "-");
}

function baseName(dir: string): string {
  return dir.split(/[\\/]/).filter(Boolean).pop() ?? "project";
}
